# Generated by Django 2.1.4 on 2019-05-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoFAlgorithm',
            fields=[
                ('idFoF', models.AutoField(primary_key=True, serialize=False)),
                ('nameFoF', models.CharField(max_length=100)),
                ('descFoF', models.TextField(null=True)),
                ('commandFoF', models.TextField()),
            ],
            options={
                'db_table': 'fof_algorithm',
                'managed': True,
            },
        ),
    ]
